### PR TITLE
added numpy lib import

### PR DESCRIPTION
**Pull request by grburgess**

### CODE REVIEW

**Comment by esheldon** [comment]
Can you give the context for this change? On what system/python/numpy version did it fail?

**Comment by grburgess** [comment]
When running python setup.py install,
my system complained about not finding the c bindings of Numpy.
OSX/hombrew python/ 

python 2.7 /  numpy '1.11.0'

This addition just makes sure that the bumpy headers are found

**Comment by esheldon** [comment]
Is it true that the include_dirs should also be removed from the setup() call?

**Comment by grburgess** [comment]
It doesn't seem to conflict, but I think that adding it to the Extension binds things... not sure that it is just a feature of my system though

**Comment by esheldon** [comment]
I checked that this works on my system as well.  I also removed it from the setup() call.

I've pushed to master, please give it a try.

**Comment by grburgess** [comment]
Thanks!

**Comment by esheldon** [comment]
If it doesn't work for you please open a new issue. I'll close this pull request.

**Pull request closed without merging**
